### ISSUE TITLE
off topic

### ISSUE THREAD

**Issue by pizzav-xyz** [JamesGreen31/JamesGreen31.github.io#1]
sorry for asking here but i would like your help, what is your discord
![image](https://github.com/JamesGreen31/JamesGreen31.github.io/assets/103120356/274804c4-b1bf-48ba-869c-0ee355d9b3dd)

**Comment by JamesGreen31** [comment]
IF you are in the alto clef server, ping me there. If not, join that server.

**Comment by pizzav-xyz** [comment]
> IF you are in the alto clef server, ping me there. If not, join that server.

whats your username?

**Comment by JamesGreen31** [comment]
ieatwallets
